version: '3.7'

#TODO: 
# 1. add nestjs project (backend).
# 2. add reactjs project frontend).

services:
  postgres_db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  #TODO: 目前直接採用 DBeaver, pgadmin會有設定問題待解決!
  # pgadmin:
  #   image: dpage/pgadmin4:latest
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${USER_EMAIL} # 使用者帳號
  #     PGADMIN_DEFAULT_PASSWORD: ${PASSWORD} # 使用者密碼
  #     PGADMIN_LISTEN_PORT: 80
  #   ports:
  #     - "8081:80"
  #   volumes:
  #     - pgadmin-data:/var/lib/pgadmin
  #   links:
  #     - "postgres_db:pgsql-server" # 在postgres下的設定: host name/address

volumes:
  db-data:
  pgadmin-data:

# networks:
#   server-net:
#     driver: bridge